package com.example.raitha_varta.ui

data class AppStrings(
    val navCrops: String,
    val navTips: String,
    val navMarket: String,
    val navExpert: String,
    val navStories: String,
    val navSettings: String,
    val cropsDashboardTitle: String,
    val cropsSearchHint: String,
    val cropsDailyTips: String,
    val weatherCurrentClimate: String,
    val weatherSyncing: String,
    val weatherOffline: String,
    val marketTitle: String,
    val marketSearchHint: String,
    val marketNoResults: String,
    val marketUpdated: String,
    val settingsTitle: String,
    val settingsLocation: String,
    val settingsDistrictHint: String,
    val settingsPrimaryCrop: String,
    val settingsLanguage: String,
    val settingsSave: String,
    val expertTitle: String,
    val expertLandingTitle: String,
    val expertLandingSubtitle: String,
    val expertTapToPhoto: String,
    val expertUploadGallery: String,
    val expertTip: String,
    val expertPrevQueries: String,
    val expertNoHistory: String,
    val expertChat: String,
    val expertAskPlaceholder: String,
    val storiesTitle: String,
    val storiesSubtitle: String,
    val storiesNewBadge: String,
    val storiesDetailsTitle: String,
    val storiesWhatDone: String,
    val storiesProblems: String,
    val storiesHowOvercame: String,
    val storiesSteps: String
)

fun appStrings(languageCode: String): AppStrings {
    return if (languageCode == "kn") {
        AppStrings(
            navCrops = "ಬೆಳೆಗಳು",
            navTips = "ಸಲಹೆಗಳು",
            navMarket = "ಮಾರುಕಟ್ಟೆ",
            navExpert = "ತಜ್ಞರನ್ನು ಕೇಳಿ",
            navStories = "ಯಶೋಗಾಥೆಗಳು",
            navSettings = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            cropsDashboardTitle = "ನನ್ನ ಫಾರ್ಮ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            cropsSearchHint = "ಬೆಳೆ ಹುಡುಕಿ (ಉದಾ: ಟೊಮ್ಯಾಟೊ)",
            cropsDailyTips = "ದೈನಂದಿನ ಸಾಮಾನ್ಯ ಸಲಹೆಗಳು",
            weatherCurrentClimate = "ಪ್ರಸ್ತುತ ಹವಾಮಾನ",
            weatherSyncing = "ಹವಾಮಾನ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",
            weatherOffline = "ಹವಾಮಾನ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ",
            marketTitle = "ಮಾರುಕಟ್ಟೆ ದರಗಳು",
            marketSearchHint = "ಬೆಳೆ ಅಥವಾ ಮಾರುಕಟ್ಟೆ ಹುಡುಕಿ...",
            marketNoResults = "ಫಲಿತಾಂಶಗಳಿಲ್ಲ",
            marketUpdated = "ನವೀಕರಿಸಲಾಗಿದೆ",
            settingsTitle = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            settingsLocation = "ಸ್ಥಳ (ಜಿಲ್ಲೆ)",
            settingsDistrictHint = "ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಹೆಸರು ನಮೂದಿಸಿ",
            settingsPrimaryCrop = "ಮುಖ್ಯ ಬೆಳೆ",
            settingsLanguage = "ಭಾಷೆ",
            settingsSave = "ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ",
            expertTitle = "ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ",
            expertLandingTitle = "ತಜ್ಞ ಸಹಾಯ",
            expertLandingSubtitle = "Expert Ask: Farmers can upload a crop image and contact agricultural experts for guidance. (Prototype Feature)",
            expertTapToPhoto = "ಫೋಟೋ ತೆಗೆಯಲು ಸ್ಪರ್ಶಿಸಿ",
            expertUploadGallery = "ಅಥವಾ ಗ್ಯಾಲರಿಯಿಂದ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
            expertTip = "Expert Ask: Farmers can upload a crop image and contact agricultural experts for guidance. (Prototype Feature)",
            expertPrevQueries = "ಹಿಂದಿನ ಪ್ರಶ್ನೆಗಳು",
            expertNoHistory = "ಹಿಂದಿನ ಪ್ರಶ್ನೆಗಳಿಲ್ಲ.",
            expertChat = "ತಜ್ಞ ಚಾಟ್",
            expertAskPlaceholder = "ನಿಮ್ಮ ಬೆಳೆ ಬಗ್ಗೆ ಕೇಳಿ...",
            storiesTitle = "ಯಶೋಗಾಥೆಗಳು",
            storiesSubtitle = "ಹೊಲದಿಂದ ಪ್ರೇರಣೆ",
            storiesNewBadge = "ಹೊಸ ಕಥೆ",
            storiesDetailsTitle = "ಕಥೆ ವಿವರಗಳು",
            storiesWhatDone = "ಅವರು ಮಾಡಿದುದು",
            storiesProblems = "ಎದುರಿಸಿದ ಸಮಸ್ಯೆಗಳು",
            storiesHowOvercame = "ಅವರು ಹೇಗೆ ಎದುರಿಸಿದರು",
            storiesSteps = "ಅನುಸರಿಸಿದ ಹಂತಗಳು"
        )
    } else {
        AppStrings(
            navCrops = "Crops",
            navTips = "Tips",
            navMarket = "Market",
            navExpert = "Expert Ask",
            navStories = "Stories",
            navSettings = "Settings",
            cropsDashboardTitle = "My Farm Dashboard",
            cropsSearchHint = "Search crops (e.g. Tomato)",
            cropsDailyTips = "View Daily General Tips",
            weatherCurrentClimate = "Current Climate",
            weatherSyncing = "Syncing weather...",
            weatherOffline = "Weather info offline",
            marketTitle = "Market Prices",
            marketSearchHint = "Search crop or market...",
            marketNoResults = "No results for",
            marketUpdated = "Updated",
            settingsTitle = "Settings",
            settingsLocation = "Location (District)",
            settingsDistrictHint = "Enter your district",
            settingsPrimaryCrop = "Primary Crop",
            settingsLanguage = "Language",
            settingsSave = "SAVE PREFERENCES",
            expertTitle = "Consult an Expert",
            expertLandingTitle = "Expert Ask",
            expertLandingSubtitle = "Expert Ask: Farmers can upload a crop image and contact agricultural experts for guidance. (Prototype Feature)",
            expertTapToPhoto = "Tap to Take Photo",
            expertUploadGallery = "or upload from gallery",
            expertTip = "Expert Ask: Farmers can upload a crop image and contact agricultural experts for guidance. (Prototype Feature)",
            expertPrevQueries = "Previous Queries",
            expertNoHistory = "No consultation history found.",
            expertChat = "Expert Chat",
            expertAskPlaceholder = "Ask about your plant...",
            storiesTitle = "Success Stories",
            storiesSubtitle = "Inspiration from the Field",
            storiesNewBadge = "NEW STORY",
            storiesDetailsTitle = "Story Details",
            storiesWhatDone = "What He Has Done",
            storiesProblems = "Problems Faced",
            storiesHowOvercame = "How He Overcame",
            storiesSteps = "Steps Taken"
        )
    }
}
